spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zone?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: "0523"